/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    PlayerControls: typeof import('./../components/PlayerControls.vue')['default']
    PlaylistPanel: typeof import('./../components/PlaylistPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongList: typeof import('./../components/SongList.vue')['default']
  }
}
